version: "3.7"

services:
  postgres-prod:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: projetos_web_prod
      POSTGRES_USER: ghd_user_prod
      POSTGRES_PASSWORD: "Pamonhapamonha191_"
      TZ: America/Sao_Paulo

    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

    command: >
      postgres
      -c listen_addresses='*'
      -c max_connections=200
      -c shared_buffers=256MB
      -c work_mem=8MB
      -c maintenance_work_mem=64MB
      -c effective_cache_size=768MB
      -c log_min_duration_statement=200

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ghd_user_prod -d projetos_web_prod"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - projetos-web

    restart: unless-stopped

volumes:
  postgres_data_prod:
    name: postgres_data_prod

networks:
  projetos-web:
    external: true
    name: projetos-web
