version: "3.9"

networks:
  projetos-web:
    external: true
    name: projetos-web

services:
  vfs-app-ssr:
    image: ghcr.io/troquatte/vfs-app-ssr-dev:latest
    container_name: vfs-app-ssr-dev

    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      DATABASE_URL: ${DATABASE_URL}
      MINIO_REGION: ${MINIO_REGION}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ASSETS: ${MINIO_ASSETS}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      SEND_EMAIL: ${SEND_EMAIL}
      SEND_EMAIL_PASSWORD: ${SEND_EMAIL_PASSWORD}
    networks:
      - projetos-web
    labels:
      - "traefik.enable=true"

      # 🚦 Router
      - "traefik.http.routers.vfs.rule=Host(`app-dev.vidafullstack.academy`) && PathPrefix(`/`)"
      - "traefik.http.routers.vfs.entrypoints=websecure"
      - "traefik.http.routers.vfs.tls=true"
      - "traefik.http.routers.vfs.tls.certresolver=letsencryptresolver"

      #  Service (porta interna do container)
      - "traefik.http.services.vfs.loadbalancer.server.port=4000"

      # 🛡️ Cabeçalhos (opcional)
      - "traefik.http.middlewares.vfs-sec.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.vfs-sec.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.vfs-sec.headers.customResponseHeaders.Referrer-Policy=strict-origin-when-cross-origin"
      - "traefik.http.routers.vfs.middlewares=vfs-sec"
