name: build-and-push-ssr

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ----------------------------- BUILD E PUSH ----------------------------- #
      - name: Build & Push (PROD)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/vfs-app-ssr-prod:latest
            ghcr.io/${{ github.repository_owner }}/vfs-app-ssr-prod:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push (DEV)
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-dev
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/vfs-app-ssr-dev:latest
            ghcr.io/${{ github.repository_owner }}/vfs-app-ssr-dev:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
